### ISSUE TITLE
OPC UA server plugin not starting and UA EXPERT cannot be connected!!!

### ISSUE THREAD

**Issue by vpvikasp** [eclipse-aaspe/aasx-server#175]
Can anyone help me out with this issue??
![OPC FAILURE](https://github.com/admin-shell-io/aasx-server/assets/130986937/a52d88bb-804e-42bb-a27a-e26f459595ed)

**Comment by aorzelskiGH** [comment]
In fact this belongs to Package Explorer.
I am not sure if this plugin works again in V3.
