### ISSUE TITLE
REST-Api: GET shells/{aasId as base64url} returns InternalServerError

### ISSUE THREAD

**Issue by simplan-niklas** [eclipse-aaspe/aasx-server#187]
I'm running the latest Blazor-Release as a docker container. 
The gui interface seems to be working. 

When I try the following:
* GET /shells
* base64url encode the "id" property of the first available AAS
* GET /shells/{id}

I get the following response:
```json
{
    "messages": [
        {
            "code": "InternalServerError",
            "correlationId": null,
            "messageType": "Error",
            "text": "Object reference not set to an instance of an object.",
            "timestamp": "10/13/2023 07:10:10"
        }
    ]
}
```

Does anyone have an idea if I'm doing anything wrong?

**Comment by aorzelskiGH** [comment]
Please try the newest version. There where some issues with empty lists.

**Comment by juileetikekar** [comment]
Hi @simplan-niklas,

Could you please provide an update, if you faced the issue again with the latest cersion as well? If yes, could you please provide further information, e.g., AASX File (if possible), complete logs, etc?

**Comment by simplan-niklas** [comment]
Hi, 

sorry we switched to another AAS-Server component (not related to this problem) and I'm currently unable to invest the time to reproduce this problem with the newer versions. 
Should this change in the future I will reopen this issue. Thanks for your support.
