### ISSUE TITLE
Outdated Swagger version

### ISSUE THREAD

**Issue by heidrjeSICKAG** [eclipse-aaspe/aasx-server#196]
The current swagger version is slightly outdated and has some moderate security issues
https://github.com/advisories/GHSA-qrmm-w75w-3wpx
An upgrade to 6.5.0 should fix that,

**Comment by heidrjeSICKAG** [comment]
I've just seen that dependabot already did try that 😄 
https://github.com/admin-shell-io/aasx-server/pull/178
https://github.com/admin-shell-io/aasx-server/pull/179
https://github.com/admin-shell-io/aasx-server/pull/180

**Comment by juileetikekar** [comment]
Hi @heidrjeSICKAG ,

Thank you for raising the issue.

We are working on it.

**Comment by juileetikekar** [comment]
Hi @heidrjeSICKAG,

The issue has been fixed in the main branch.
