### ISSUE TITLE
Invalid server profile

### ISSUE THREAD

**Issue by mhrimaz** [eclipse-aaspe/aasx-server#198]
Current profile output for `/description` endpoint is not valid:
![image](https://github.com/admin-shell-io/aasx-server/assets/17963017/7d9c4234-bda3-47d8-98b1-6117df2a18b7)

Expected behaviour:
![image](https://github.com/admin-shell-io/aasx-server/assets/17963017/bd742a97-8e96-47ac-a3bc-385498db5d4e)

**Comment by juileetikekar** [comment]
Hi @mhrimaz,

Thank you for bringing this issue to our notice!

We will fix the issue soon and keep you informed.
