### ISSUE TITLE
 ​/shells​/{aasIdentifier}​/submodel-refs response structure is different than swagger definition and PageResult-aascore3.0 conflict

### ISSUE THREAD

**Issue by EmilAlipiev** [eclipse-aaspe/aasx-server#203]
Swagger definition is not a pagedresult but response returned is a pagedresult as shown below.

that causes 2 issues or conflicts. 
first of all we try to use  [aas-core3.0-csharp](https://github.com/aas-core-works/aas-core3.0-csharp) to deserialize response into object but aas-core3.0 doesnt define any Paged-result. Ok, here we can get the inner "Result" json element different way but then how do you actuall deserialize this when it implements IClass interface? without doing your own workaround or customized serializable class. Because standard Serializer needs concrete objects, not interface. you may refer to [terate_copy_and_transform](https://aas-core-works.github.io/aas-core3.0-csharp/getting_started/iterate_copy_and_transform.html) but in the example there, you already need an object. So it conflicts itself as you can deserialize this. 
[jsonize](https://aas-core-works.github.io/aas-core3.0-csharp/getting_started/jsonize.html) also only implement for response as Reference string, not for ReferencePagedResult as it doesnt exist in Aascode3.0
So overall, there is a big conflict in usage and implementation here. 

![Screenshot 2023-12-06 at 14 09 48](https://github.com/admin-shell-io/aasx-server/assets/10422347/b7990ffa-e946-442d-9961-d96fb99f1888)

**Comment by juileetikekar** [comment]
Hi @EmilAlipiev,

Thank you for the query.

However, the implementation is based on AAS-Specifications part 2, which dictates to have pagination for "GetAll" requests including "GetAllSubmodelReferences". Additionally, the swagger definitions also include Pagination. Please see the screenshots below.

**Screenshots from AAS Specifications Part 2** (PDF Document)
![image](https://github.com/admin-shell-io/aasx-server/assets/99317579/0a5ec0a7-e05d-46dd-b2bb-69366e0a520d)

![image](https://github.com/admin-shell-io/aasx-server/assets/99317579/e0b58797-f883-480d-8ecd-a2289f611117)

![image](https://github.com/admin-shell-io/aasx-server/assets/99317579/c5a85f5e-7cc0-4962-8c97-8a8b9aa4d315)

**Screenshot from Swagger Definition:**
![image](https://github.com/admin-shell-io/aasx-server/assets/99317579/ab4cc8cd-a7b9-4dea-b24d-b23aaa2a1a5e)
