### ISSUE TITLE
https://v3.admin-shell-io.com/ is down!

### ISSUE THREAD

**Issue by mrentsch65** [eclipse-aaspe/aasx-server#206]
Hello,
i want to inform, that https://v3.admin-shell-io.com/ is not reachable any more.

**Comment by juileetikekar** [comment]
Hi @mrentsch65,

Thank you for informing. We are working on it.

**Comment by juileetikekar** [comment]
Hi @mrentsch65,

The https://v3.admin-shell-io.com/ server is up and running.
