### ISSUE TITLE
HasDataSpecification Deserialization Bug

### ISSUE THREAD

**Issue by ChrisConclurer** [eclipse-aaspe/aasx-server#217]
- Throws 500 error if "dataSpecifications" are included in the serialization
- Was tested with repository interface operation PostAssetAdministrationShell (Part 2 7.2.6)
- Operation ID: https://admin-shell.io/aas/API/PostAssetAdministrationShell/3/0
- The server instead uses "embeddedDataSpecifications" which is not part of the metamodel, see HasDataSpecification (Part 1 5.3.2.3)
- embeddedDataSpecifications is currently also not part of the official OpenAPI Schema [HasDataSpecification](https://app.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V3.0RC02#/components/schemas/HasDataSpecification)
- The property "dataSpecifications" is part of the model and defined as an array of references

The embedded data specifications are not yet included in the documentation or have been removed from a previous version. In my opinion the presence of dataSpecifications should not throw an internal server error. If it can be deserialized right now then it would be best to just ignore it and perhaps in general additional JSON properties should not lead to an error but they should just be ignored.

**Comment by juileetikekar** [comment]
Hi @ChrisConclurer,

In the document "Specification of the Asset Administration Shell Part 1: Metamodel", section 7.2 defines general rules for the serialization. Under this section, sub-section 7.2.5, defines the use of EmbeddedDataSpecification in case of serialization of data specifications. Based on this, the de/serialization logic of AASX Server also treats the HasDataSpecification as a list of EmbeddedDataSpecifications.

Screenshot: Figure 58 from "Specification of the Asset Administration Shell Part 1: Metamodel"

![image](https://github.com/eclipse-aaspe/aasx-server/assets/99317579/3547e71b-5d39-45d7-88be-ecb796a7d92b)
