### ISSUE TITLE
Blazor dowload shows error

### ISSUE THREAD

**Issue by TNeis** [eclipse-aaspe/aasx-server#220]
Starting the example server and use download of the aasx file shows an error in console window:
![image](https://github.com/admin-shell-io/aasx-server/assets/64397748/6aa595ab-3839-44a0-afe4-631e6cda630d)

The browser opens a new tab and shows the following:
![image](https://github.com/admin-shell-io/aasx-server/assets/64397748/eb572dab-c7c8-4eb7-8d99-dc7361c98200)

There was no temp file existing before. As a result, two temp files are created by the server (related to #123).

**Comment by juileetikekar** [comment]
Hi @TNeis,

Thank you for raising the issue. Could you please share if you are using docker, release or code and the corresponding version? We would also appreciate if you could share the steps to reproduce the issue.

**Comment by TNeis** [comment]
Hi @juileetikekar 

Thanks for the fast response! I'm using the latest release [AasxServerBlazor.2023-11-17.alpha.zip](https://github.com/eclipse-aaspe/aasx-server/releases/download/v2023-11-17.alpha/AasxServerBlazor.2023-11-17.alpha.zip)

I'm running the server locally on my Windows 10 machine (for easy testing of a client I'm developing). So no docker involved.

Repro steps:
1. Download and unzip above package
2. Execute the startForDemo.bat file
3. Open Blazor server in Chrome with URL: http://localhost:5001/
4. Select contained Example package and click the download link on the right. In this case "http://localhost:5001/packages/MA"
-> The error will be shown like in the screenshot of the issue

**Comment by juileetikekar** [comment]
Hi @TNeis,

Thank you for the information.

The issue was successfully reproduced. We'll keep you updated.

**Comment by juileetikekar** [comment]
Hi @TNeis,

The issues has been fixed and merged into main branch.
