### ISSUE TITLE
duplicate argument

### ISSUE THREAD

**Issue by TNeis** [eclipse-aaspe/aasx-server#222]
When calling the server from cmd and using the "-h" option an error is shown that argument for -h option is missing but I only wanted to show the help. Issue here is that the -h option is offered for the "help" and "host" option.

![image](https://github.com/admin-shell-io/aasx-server/assets/64397748/20103ca1-4eb0-4f0e-84d7-3e0094951352)

**Comment by juileetikekar** [comment]
Hi @TNeis ,

The issue has been fixed and merged into main branch.
