### ISSUE TITLE
InternalServerError GET /submodels/{id}/submodel-elements/{idshortpath}/attachment

### ISSUE THREAD

**Issue by cbiehl30** [eclipse-aaspe/aasx-server#224]
The server returns 500 InternalServerError when requesting `GET /submodels/{id}/submodel-elements/{idshortpath}/attachment`:
```
{
  "messages": [
    {
      "code": "InternalServerError",
      "correlationId": null,
      "messageType": "Error",
      "text": "AASX Package New Package not opened. Aborting!",
      "timestamp": "02/21/2024 12:00:19"
    }
  ]
}
```

Steps for reproducing:
1. Create a submodel via `POST /submodels`
```
{
  "idShort": "abc",
  "id": "123",
  "submodelElements": [
    {
      "idShort": "def",
      "typeValueListElement": "File",
      "value": [
        {
          "idShort": "some_pdf",
          "contentType": "application/pdf",
          "modelType": "File"
        }
      ],
      "modelType": "SubmodelElementList"
    }
  ],
  "modelType": "Submodel"
}
```

2. Send a file to `PUT /submodels/MTIz/submodel-elements/def.some_pdf/attachment`
3. `GET /submodels/MTIz/submodel-elements/def.some_pdf/attachment`

I'm using the docker version as described in the readme. Is there something I am doing wrong maybe?

**Comment by juileetikekar** [comment]
Hi @cbiehl30,

As per the current implementation, there has to be an AASX Package available for a supplementary file to be added to the package (Put /.../attachement). 

From the step 1 to reproduce the issue, I assume, the sumodel is not being added to any partifular AAS as well.

To resolve this issue, please follow below steps:

1. Create an AAS, if already not available.
2. Create a submodel to the AAS using an API " Post /submodels" (screenshot 1 in the end) and provide the aasIdentifier from step 1.
3. Download the AASX Package using the API "Get /packages/{packageId}" (screenshot 2). This step will create an AASX Package. If you are using Blazor version of the server, you will find the package id as per the screenshot 3. In this screenshot "MA" is the already encoded packageId. For simplicity, you can also click on the link from the blazor UI, to download the package.
4. Now, upload a file to the submodel.

Screenshot 1:
![image](https://github.com/eclipse-aaspe/aasx-server/assets/99317579/b66ec8a6-2ac0-4616-b644-6c027c8bdc98)

Screenshot 2:
![image](https://github.com/eclipse-aaspe/aasx-server/assets/99317579/d82890f8-3192-41f3-a5b4-26b8ecc9b9ac)

Screenshot 3:
![image](https://github.com/eclipse-aaspe/aasx-server/assets/99317579/f80e769a-f50d-4fd1-86c6-82ecfd3376cc)

**Comment by cbiehl30** [comment]
@juileetikekar Thank you for explaining, it works the way you described it
