### ISSUE TITLE
[Not a Bug]: Server V3 down

### ISSUE THREAD

**Issue by Kuchsn** [eclipse-aaspe/aasx-server#227]
### Describe the bug

The Server: [https://v3.admin-shell-io.com/](https://v3.admin-shell-io.com/) is now down for at least 2 day's.
I already wrote a email to IDTA which is mentioned in the Imprint. But no reaction.

### To reproduce

klick link: [https://v3.admin-shell-io.com/](https://v3.admin-shell-io.com/)

### Expected Behaviour

working server or if the server got shut down remove the links.

**Comment by martafullen** [comment]
Hi @Kuchsn, unfortunately we are struggling with some issues which cause v3.admin-shell-io.com to repeatedly crash and not restart the service. We are working on a fix.
