### ISSUE TITLE
[Bug]: Unable to Access API Endpoints as Described in README

### ISSUE THREAD

**Issue by yoko-takano** [eclipse-aaspe/aasx-server#246]
**Description:**

I'm encountering difficulties accessing the API endpoints as described in the README of the repository. Specifically, I'm trying to access the endpoints mentioned under /aas/ExampleMotor, but I keep receiving a "Sorry, there's nothing at this address" message.

**Steps to Reproduce:**

Clone the repository.
Follow the setup instructions provided in the README.
Attempt to access the /aas/ExampleMotor endpoints using the specified base URL.
Observe the error message.
Additionally, I can confirm that I am able to access the server successfully when using localhost:5001, and I'm able to see the AAS ExampleMotor.

**Expected Behavior:**

According to the README, I should be able to access the API endpoints under /aas/ExampleMotor after setting up the server using the base URL http://localhost:5001. However, I'm unable to access these endpoints.

Please let me know if there are any additional steps I should take or if there's any further information needed to troubleshoot this issue. Thank you!

**Comment by juileetikekar** [comment]
Hi @yoko-takano,

Thank you for your query!!

The API that you are using "/aas/ExampleMotor" belong to the old implementation. The are no more applicable to the latest implementation. It is listed under "Old Documentation" in README file.

In the latest implementation, please find the API endpoints in Swagger UI at "http://localhost:5001/swagger/index.html".

For example, if you need to request a shell, you can use below API. 
**Please note: the field "aasIdentifier" is Base64URLEncoded "aasId"**

![image](https://github.com/eclipse-aaspe/aasx-server/assets/99317579/c030ef54-5443-462c-9921-903297a3db78)
